language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
env:
  - CXX=g++-4.8
sudo: false
os:
  - linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - autoconf
      - libssl0.9.8
      - libssl-dev
      - liblua5.1
      - liblua5.1-dev
install:
  - wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
  - tar xvzf aerospike-server.tgz
  - cp -f .travis/aerospike.conf ./aerospike-server/share/etc
  - cd aerospike-server
  - sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
  - sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
  - sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start  
  - mkdir instance1
  - ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
  - cd instance1
  - ./bin/aerospike start
  - cd ../..
  - sleep 5
  - tail -n 1000 aerospike-server/instance1/var/log/aerospike.log
script:
  - npm install
  - npm test
