sudo: true

language: node_js

node_js:
  - 0.10

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  - ./run docker run -it -p "3000:3000" sunnybhanot/aerospike
  - sleep 5

script:
  - npm install
  - npm test
